[package]
edition = "2021"
name = "cpe_analyzer"
version = "0.1.0"

[dependencies]
reqwest = "0.11"
rusqlite = "0.28"
serde = "1.0"
serde_json = "1.0"
tokio = {version = "1.21", features = ["full"]}
xml-rs = "0.8"
zip = "0.6"
