[package]
edition = "2021"
name = "cpe_analyzer"
version = "0.1.0"

[dependencies]
log = "0.4"
reqwest = "0.11"
rusqlite = "0.28"
serde = "1.0"
serde_json = "1.0"
tokio = {version = "1.21", features = ["full"]}
tracing = "0.1"
tracing-subscriber = "0.3"
xml-rs = "0.8"
zip = "0.6"
